# Copyright Altran Netherlands B.V

project: espilce-polvi
language: Java
default_branch: "develop"
code_location:
  source:
    - ./component/
artifact_repository_url: "https://nexus.acidspace.nl/repository/{}/{}{}"

build:
  binaries:
    platform: Maven
    precondition:
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      output: ./reports/build/binaries
      build_settings_path: ./settings.xml
      build_pom_path: ./releng/org.espilce.polvi.parent/pom.xml

test:
  units:
    platform: Maven
    precondition:
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      output: ./reports/test/units
      test_settings_path: ./settings.xml
      test_pom_path: ./releng/org.espilce.polvi.parent/pom.xml
      index: test-units

release:
  binaries:
    platform: P2
    precondition:
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      repository: espilce-polvi
      repository_project: ./releng/org.espilce.polvi.repository
      output: ./reports/release/binaries