# Copyright Altran Netherlands B.V

stages:
  - build
  - check
  - test
  - publish
  - smoke
  - acceptance
  - performance
  - manual
  - release

variables:
  REGISTRY_URL: registry.acidspace.nl

  MAVEN_CONTAINER: acid/container/maven:0.16.1

espilce-polvi:
  image: ${REGISTRY_URL}/${MAVEN_CONTAINER}
  stage: build
  tags:
    - linux_docker
  script:
   - chmod -R +x ./releng/scripts
   - ./releng/scripts/build.sh
  artifacts:
    when: always
    paths:
      - "component/*/*/target/*.jar"
      - "component/*/*/target/surefire-reports/*.dump"
      - "component/*/*/target/surefire-reports/*.dumpstream"
    reports:
      junit: "component/*/*/target/surefire-reports/*.xml"
    expire_in: 4 weeks
  dependencies: []

release:
  image: ${REGISTRY_URL}/${MAVEN_CONTAINER}
  tags:
    - linux_docker
  stage: publish
  script:
    - acidcli release binaries
  artifacts:
    paths:
      - release/binaries/
    expire_in: 4 weeks
    when: always
  dependencies: []
